'========================= CONVOCATION DATABASE COLOR BUTTONS ========================='
'Created By: Brady Hammond
'Created: 05/02/16
'======================================================================================'

'Color Green Subroutine:
Sub Green_Button()
    
    'Color the selected rows green
    Selection.Interior.ColorIndex = 35
    
End Sub

'Color Pink Subroutine:
Sub Pink_Button()
    
    'Color the selected rows pink
    Selection.Interior.ColorIndex = 38
    
End Sub

'Color Red Subroutine:
Sub Red_Button()

    'Color the selected rows red
    Selection.Interior.ColorIndex = 3
    
End Sub

'Color Yellow Subroutine:
Sub Yellow_Button()

    'Color the selected rows yellow
    Selection.Interior.ColorIndex = 36
    
End Sub

'Color White Subroutine:
Sub White_Button()

    'Color the selected rows white
    Selection.Interior.ColorIndex = 0
    
End Sub

